# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchook', '0002_auto_20161013_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='user',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
