# Generated by Django 2.1.2 on 2018-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchook', '0003_auto_20181028_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
