# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_series_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
