# Generated by Django 2.0 on 2018-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
    ]
