# Generated by Django 2.0 on 2018-09-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_isbnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbnbook',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Series'),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('archived', 'Removed')], default='current', max_length=20),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='user',
            field=models.CharField(blank=True, default='admin', max_length=200, null=True),
        ),
    ]
